[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'runtime',
]

#[patch."https://github.com/integritee-network/pallets.git"]
#pallet-claims = { path = '../pallets/claims' }
#pallet-teerex = { path = '../pallets/teerex' }
#pallet-teeracle = { path = '../pallets/teeracle' }

################################################################################
# [patch."https://github.com/Interstellar-Network/pallets.git"]
# ocw-common = { path = "../pallets/ocw-common/" }
# pallet-ocw-circuits = { path = "../pallets/pallets/ocw-circuits/" }
# pallet-tx-registry = { path = "../pallets/pallets/tx-registry/" }
################################################################################