name: CI

on:
  push:

jobs:
  # TODO split test and lint; but that REQUIRE caching else recompile from scratch in between
  rust:
    runs-on: ubuntu-latest
    steps:
      # # install build dependencies
      # # MUST match the same step in Dockerfile
      # - name: Install dependencies
      #   run: sudo apt-get update && sudo apt-get install -y libboost-dev

      - uses: Interstellar-Network/gh-actions/prepare@v2
        with:
          ssh_key_input: ${{ secrets.SSH_KEY_MACHINE_USER_INTERSTELLAR_CI }}
          install_cmake_and_ninja: false
          install_ccache: true
          install_conan: false

      # TODO? llvm? or is gcc enough(already installed by Interstellar-Network/gh-actions/prepare)
      # - name: Install llvm-10
      #   run: sudo apt-get install llvm-10 clang-10

      - uses: Interstellar-Network/gh-actions/prepare_rust@v2
        with:
          skip_action_toolchain: "true"

      # TODO pass "--features skip-ias-check,skip-extrinsic-filtering"; to cargo check? and/or cargo test?

      - uses: Interstellar-Network/gh-actions/rust-build-and-test@v2

      - uses: Interstellar-Network/gh-actions/rust-lint@v2
